# Generated by Django 3.1.1 on 2020-09-27 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Clientfeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('image', models.ImageField(upload_to='Clinet feedback')),
                ('rating', models.IntegerField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Division',
                'verbose_name_plural': '1. Division',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Location Image')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.city')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.division')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': '2. Location',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='travel.location')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': '3. Package',
            },
        ),
        migrations.CreateModel(
            name='PackageVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='travel.package')),
            ],
            options={
                'verbose_name': 'Package Video',
                'verbose_name_plural': '7. Package Videos',
            },
        ),
        migrations.CreateModel(
            name='PackageSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='travel.package')),
            ],
            options={
                'verbose_name': 'Package Schedule',
                'verbose_name_plural': '5. Package Schedule',
            },
        ),
        migrations.CreateModel(
            name='PackageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='package')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='travel.package')),
            ],
            options={
                'verbose_name': 'Package Image',
                'verbose_name_plural': '4. Package Images',
            },
        ),
        migrations.CreateModel(
            name='PackageExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('avialable', models.CharField(choices=[('1', 'Avialable'), ('2', 'Not Avialable'), ('3', 'May Be')], max_length=10)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='travel.package')),
            ],
            options={
                'verbose_name': 'Package Extra',
                'verbose_name_plural': '6. Package Extra',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.division'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.package')),
            ],
        ),
    ]
