# Generated by Django 3.1.1 on 2020-09-15 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': '2. Package',
            },
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Location', 'verbose_name_plural': '1. Location'},
        ),
        migrations.CreateModel(
            name='PackageVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='travel.package')),
            ],
            options={
                'verbose_name': 'Package Video',
                'verbose_name_plural': '5. Package Videos',
            },
        ),
        migrations.CreateModel(
            name='PackageSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='travel.package')),
            ],
            options={
                'verbose_name': 'Package Schedule',
                'verbose_name_plural': '5. Package Schedule',
            },
        ),
        migrations.CreateModel(
            name='PackageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='package')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='travel.package')),
            ],
            options={
                'verbose_name': 'Package Image',
                'verbose_name_plural': '5. Package Images',
            },
        ),
        migrations.CreateModel(
            name='PackageExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('avialable', models.CharField(choices=[('1', 'Avialable'), ('2', 'Not Avialable'), ('3', 'May Be')], max_length=10)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='travel.package')),
            ],
            options={
                'verbose_name': 'Package Extra',
                'verbose_name_plural': '5. Package Extra',
            },
        ),
        migrations.AddField(
            model_name='package',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='travel.location'),
        ),
    ]
