# Generated by Django 3.1.1 on 2020-09-15 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20200915_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='place',
            new_name='area',
        ),
    ]
