# Generated by Django 3.1.1 on 2020-09-23 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_clinetfeedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clinetfeedback',
            new_name='Clientfeedback',
        ),
    ]
