# Generated by Django 3.1.1 on 2020-09-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_auto_20200915_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='division',
            field=models.CharField(default='Dhaka', max_length=200),
            preserve_default=False,
        ),
    ]
