# Generated by Django 3.1.1 on 2020-09-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_auto_20200923_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfeedback',
            name='rating',
            field=models.IntegerField(default=True),
        ),
    ]
