# Generated by Django 3.1.1 on 2020-09-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_location_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='division',
            field=models.CharField(choices=[('Dhaka', 'Dhaka'), ('Khulna', 'Khulna'), ('Rajshahi', 'Rajshahi')], max_length=200),
        ),
    ]
